language: csharp
solution: "anndotnet.cmd.core.sln"
install:
    - nuget restore anndotnet.cmd.core.sln
    - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release anndotnet.cmd.core.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe .test/anndotnet.unit/bin/x64/Debug/netcoreapp2.0/anndotnet.unit.dll